/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.test;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int order_header=0x7f050001;
        public static final int order_id1=0x7f050002;
        public static final int order_id2=0x7f050003;
        public static final int order_id3=0x7f050004;
        public static final int order_id4=0x7f050005;
        public static final int order_id5=0x7f050006;
        public static final int ordercardcontentrow=0x7f050000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int hello_msg=0x7f040001;
        public static final int string1=0x7f040002;
        public static final int string2=0x7f040003;
        public static final int string3=0x7f040004;
        public static final int string4=0x7f040005;
        public static final int string5=0x7f040006;
    }
}
